services:
  postgres:
    container_name: postgres
    image: postgres:latest
    env_file: .env
    volumes:
      # persists data in a Docker volume
      - postgres:/var/lib/postgresql/data
      # mount initialization scripts to set up the database schema and seed data
      - ./sql/:/docker-entrypoint-initdb.d
    ports:
      # only listen on localhost for added security.
      # remove 127.0.0.1 to listen on all interfaces.
      - 127.0.0.1:5432:5432

  app:
    build: ./app
    container_name: app
    env_file: .env
    ports:
      # only listen on localhost for added security.
      # remove 127.0.0.1 to listen on all interfaces.
      - 127.0.0.1:3333:3333

volumes:
  postgres:
